name: RBF
version: '${project.version}'
main: me.ajmac.contactflag.RBF
api-version: 1.19
depend: [WorldGuard]
authors: [AjMac]
description: WorldGuard flag to prevent sweet berry bush damage
website: https://ajmaacc.com
